### ISSUE TITLE
Save browser tabs in PinBuddy

### ISSUE THREAD

**Issue by krzysztofzuraw** [pawelgrzybek/PinBuddy#33]
Hi!
Thank you for this extension - it works great! I have a feature request - I remember that pinboard has tabs sets. It will be great if PinBuddy can have such option too! I could help develop such feature 😄

**Comment by pawelgrzybek** [comment]
Hi.

Thanks for using PinBuddy. I have a good and bad news. Good: I really want to add browser tabs in PinBuddy too. Bad one: there is no API for it :(

https://pinboard.in/api

Have a great day Krzysiu 📌

**Comment by krzysztofzuraw** [comment]
🤔 what about having link/button/something that will redirects user to https://pinboard.in/tabs/show/?
 I know that there is already an extension for that in [chrome store](https://chrome.google.com/webstore/detail/save-tabs-set-to-pinboard/ehddnmgofimbganchpecibdhmdlaghno?hl=en). Yet user need to have two different extensions installed & I cannot find source code for chrome store one. 
What do you think?
